---
title: "Longer trips"
execute:
  echo: false
  warning: false
  error: false
---

```{r "imports and variables - longer trips"}
source("source.R")
```

```{r "Compute some dfs - longer trips"}

hours <- seq(0,24,1)
distance <- seq(0,500,10)

costs_dfs = list()

for (
  plan_name in names(
    station_based_plans
  )
) {
  if (
    !(
      plan_name %in% c(
        "flex",
        "value_extra_workday"
      )
    )
  ) {
    costs_dfs[[plan_name]] <- get_costs(
      station_based_plans[[plan_name]],
      hours,
      distance
    )
  }
}

max_cost <- max(
  unlist(
    lapply(
      costs_dfs,
      \(x) max(
        x$total_cost
      )
    )
  )
)

best_cost_df <- costs_dfs |>
  bind_rows() |>
  group_by(
    hours,
    distance
  ) |>
  arrange(
    total_cost,
    plan_name,
    .by_group = TRUE
  ) |>
  mutate(
    tooltip = paste0(
      hours,
      " hours, ",
      distance,
      "km:\n---\n",
      plan_name,
      ": $",
      total_cost,
      " ($",
      time_cost,
      " + $",
      distance_cost,
      ")\n",
      collapse=""
    )
  ) |>
  slice_min(
    total_cost
  )
```

## Best plan

```{r "best plan heatmap"}
p <- ggplot(
  best_cost_df,
  aes(
    hours,
    distance,
    fill=plan_name,
    text=tooltip
  )
) + 
  geom_tile() +
  labs(
    fill = "Plan",
    x = "Hours",
    y = "Distance (km)"
  ) +
  scale_fill_paletteer_d(
    "nationalparkcolors::Acadia"
  ) +
  theme_minimal() +
  theme(
    legend.position = "bottom"
  )

# p

ggplotly(
  p,
  tooltip="tooltip"
)
```

## Open

```{r "open heatmap"}
make_ggplotly(
  costs_dfs$open,
  max_cost
)
```

## Open Plus

```{r "open plus heatmap"}
make_ggplotly(
  costs_dfs$open_plus,
  max_cost
)
```
## Value

```{r "value heatmap"}
make_ggplotly(
  costs_dfs$value,
  max_cost
)
```

## Value Plus

```{r "value plus heatmap"}
make_ggplotly(
  costs_dfs$value_plus,
  max_cost
)
```

## Value Extra

```{r "value extra heatmap"}
make_ggplotly(
  costs_dfs$value_extra,
  max_cost
)
```