---
title: "Medium trips"
execute:
  echo: false
  warning: false
  error: false
---

```{r "imports and variables - medium trips"}
library(renv)
library(dplyr)
library(purrr)
library(ggplot2)
library(plotly)
library(paletteer)
library(nationalparkcolors)
library(scales)

source("source.R")
```

```{r "Compute some dfs - medium trips"}

hours <- seq(0,7*24,12)
distance <- seq(0,50*7,50)

costs_dfs = list()

colour_palette <- paletteer_d("nationalparkcolors::Acadia")

plan_colours <- c(
  Open = colour_palette[[1]],
  "Open Plus" = colour_palette[[2]],
  Value = colour_palette[[3]],
  "Value Plus" = colour_palette[[4]],
  "Value Extra" = colour_palette[[5]]
)

for (
  plan_name in names(
    station_based_plans
  )
) {
  if (
    !(
      plan_name %in% c(
        "flex",
        "value_extra_workday"
      )
    )
  ) {
    colour <- plan_colours[[station_based_plans[[plan_name]]$name]]

    costs_dfs[[station_based_plans[[plan_name]]$name]] <- get_costs(
      station_based_plans[[plan_name]],
      hours,
      distance
    ) |>
    mutate(
      Colour = colour
    )
  }
}

costs_dfs[["Value"]] <- costs_dfs[["Value"]] |>
  mutate(
    open_plus_cost = costs_dfs[["Open Plus"]] |>
      select(
        total_cost
      ) |>
      pull(),
    total_cost = if_else(
      total_cost > open_plus_cost,
      open_plus_cost,
      total_cost
    )
  )

max_cost <- max(
  unlist(
    lapply(
      costs_dfs,
      \(x) max(
        x$total_cost
      )
    )
  )
)

best_cost_df <- costs_dfs |>
  bind_rows() |>
  group_by(
    hours,
    distance
  ) |>
  arrange(
    total_cost,
    plan_name,
    .by_group = TRUE
  ) |>
  mutate(
    tooltip = paste0(
      hours,
      " hours, ",
      distance,
      "km:\n---\n",
      plan_name,
      ": $",
      total_cost,
      " ($",
      time_cost,
      " + $",
      distance_cost,
      ")\n",
      collapse=""
    )
  ) |>
  slice_min(
    total_cost
  ) |>
  ungroup()
```

## Best plan

```{r "best plan heatmap"}
make_best_plan_heatmap(
  best_cost_df,
  plan_colours
)
```